var source = {
	"origin": ["<br>#fiveLine.capitalize#<br> #sevenLine.capitalize#<br> #fiveLine.capitalize#.<br><br>"],
  
  	"sevenSyl" : ["who’s going to pay for it", 
"please tell everybody",
"and if you get diagnosed", 
"get help immediately",
"I just want people to know", 
"I took all the precautions", 
"it may not have helped me but",
"I hope it helps somebody",
"do everything you can",
"I thought this was a hoax but", 
"I am sure I will come back",
"you always remember me",
"tell my daughter I love her",
"who I was and who I am",
"wish I would have got the shot",
"ventilator tomorrow",
"no matter what happens and",
"Mama I don't want to die"],
  
    "fiveSyl" : ["this is not a hoax", 
"we let our guard down", 
"to protect yourselves",
"mom be back home soon",
"anyone I love",
"this is not goodbye",
"always remember", 
"Mama I can't breathe", 
"it was a mistake", 
"shouldn’t have waited",
"immediately",
"everybody",
"take care of my girl"],
	
	"threeSyl": ["we messed up",
"a few days",
"be careful",
"this is real",
"remember",
"diagnosed",
"somebody",
"tomorrow",
"anyone",             
"I love you",
"I can’t breathe"],
	
	"twoSyl" : ["it’s real", 
"careful",
"people",
"always",
"daughter",
"get help",
"mama",
"home soon",              
"take care",
"my girl",
"goodbye"],
	
	"fiveLine": ["#fiveSyl#","#fiveSyl#", "#threeSyl# #twoSyl#", "#twoSyl# #threeSyl#"],
	
	"sevenLine" : ["#sevenSyl#","#sevenSyl#","#sevenSyl#","#sevenSyl#","#sevenSyl#","#fiveSyl# #twoSyl#","#twoSyl# #fiveSyl#","#fiveLine# #twoSyl#","#twoSyl# #fiveLine#"],
}  